# Generated by Django 3.2 on 2021-06-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsCategory',
            new_name='ProductCategory',
        ),
    ]
